include:
  - project: 'beckerlab/ci-templates'  
    ref: 'master'
    file: 'containers.yml'

build_image:
  stage: build
  extends: .build_image
  variables:
    REGISTRY: gitlab.lrz.de:5005
  rules:
    - changes:
      - Dockerfile
      - environment.yml