include:
  - project: 'beckerlab/ci-templates'  
    ref: 'master'
    file: 'containers.yml'

build_image:
  stage: build
  extends: .build_image
  parallel:
    matrix:
        - REGISTRY:
          - gitlab.lrz.de:5005
  rules:
    - changes:
      - Dockerfile
      - environment.yml

run_pipeline:
  stage: test
  tags:
   - podman
  parallel:
    matrix:
      - PARAMS: ["--phenotypes 'assets/phenotypes/FT10_mean.csv'","--multitrait --phenotypes 'assets/phenotypes/*_mean.csv'"] 
  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    #install nextflow
    - curl -s https://get.nextflow.io| bash
  script:
    - pwd
    - ./nextflow run $CI_PROJECT_DIR --genotype "$CI_PROJECT_DIR/assets/genotypes/regmap.hdf5" $PARAMS -profile test -with-podman $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - results/execution_report.html
      - results/plots/**/*.png