before_script:
  - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
after_script:
  - podman rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build_image:
  stage: build
  tags:
   - podman
  script:
    - podman build --tag $CI_REGISTRY_IMAGE .
    - podman push $CI_REGISTRY_IMAGE docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    refs:
      - branches
    changes:
      - Dockerfile
      - environment.yml

run_pipeline:
  stage: test
  tags:
   - podman
  before_script:
    #install nextflow
    - curl -s https://get.nextflow.io| bash
    #get phenotype data
    - curl -s https://arapheno.1001genomes.org/rest/phenotype/261/values.csv | cut -f2,8 -d, > FT10.csv
  script:
    - ./nextflow run $CI_PROJECT_DIR --genotype "$CI_PROJECT_DIR/assets/genotypes/regmap.hdf5" --phenotype 'FT10.csv' -profile test -with-podman $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  artifacts:
    paths:
      - results/execution_report.html
      - results/plots/**/*.png