name: gwas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - limix=3.0.4
<<<<<<< HEAD
  - pandas=1.0.5
=======
  - pyarrow=1.0.1
<<<<<<< HEAD
>>>>>>> add pyarrow dependency
=======
  - pandas=1.0.5
>>>>>>> pin pandas version to 1.0.5
